### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by rivatove** [jens-duttke/check-outdated#22]
When running:
`npx check-outdated --ignore-pre-releases --ignore-packages a,b,c --columns package,current,wanted,latest,changes`

I get the following ouput:

```
11 outdated dependencies found:

/home/.npm/_npx/1ffde889918d975b/node_modules/check-outdated/helper/list.js:21
        return entries.map(([key, value]) => (typeof value === 'string' ? value : JSON.stringify(value, null, '  ')).replace(/^/gmu, `$&${key} `)).join('\n');
                                                                                                                     ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at /home/.npm/_npx/1ffde889918d975b/node_modules/check-outdated/helper/list.js:21:111
    at Array.map (<anonymous>)
    at generateKeyValueList (/home/.npm/_npx/1ffde889918d975b/node_modules/check-outdated/helper/list.js:21:17)
    at checkOutdated (/home/.npm/_npx/1ffde889918d975b/node_modules/check-outdated/check-outdated.js:404:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/.npm/_npx/1ffde889918d975b/node_modules/check-outdated/check-outdated.js:339:22

Node.js v18.18.2
```

It used to work and broke only recently.

**Comment by jens-duttke** [comment]
Can you please share your `package.json`, or at least the dependency lists? And which `npm` version are you using?

**Comment by rivatove** [comment]
> Can you please share your `package.json`, or at least the dependency lists? And which `npm` version are you using?

I debugged further using `--ignore-packages` and the package causing the issue is `@swc/cli`.

**Comment by jens-duttke** [comment]
This problem is not reproduceable.
